export default {
  PERFORM_RATING: 'PERFORM_RATING',
  RATING_PERFORMED: 'RATING_PERFORMED',
  REQUEST_SUBMISSIONS_LIST: 'REQUEST_SUBMISSIONS_LIST',
  RECEIVE_SUBMISSIONS_LIST: 'RECEIVE_SUBMISSIONS_LIST',
  REQUEST_SUBMISSION: 'REQUEST_SUBMISSION',
  RECEIVE_SUBMISSION: 'RECEIVE_SUBMISSION'
};
